
/****************************************************************************/
/* Mavid Platform 
   ENV ID definitions created by python script: CreateEnv.py 
   Edit envitem.xml to add new ENV.
   Do not edit this file. */
/****************************************************************************/
#define ENV_Mavid_ID                   0
#define ENV_ssid_ID                    1
#define ENV_security_ID                2
#define ENV_passphrase_ID              3
#define ENV_HostComm_ID                4
#define ENV_DebugComm_ID               5
#define ENV_mac_ID                     6
#define ENV_productId_ID               7
#define ENV_refreshToken_ID            8
#define ENV_clientId_ID                9
#define ENV_productSerialNum_ID       10
#define ENV_local_ID                  11
#define ENV_notifi_visual_ID          12
#define ENV_endpoint_ID               13
#define ENV_OTAServerUrl_ID           14
#define ENV_psm_ID                    15
#define ENV_AsrpValue_ID              16
#define ENV_Source_ID                 17
#define ENV_Volume_ID                 18
#define ENV_PrivacyMode_ID            19
#define ENV_MaxAlerts_ID              20
#define ENV_Alerts1_ID                21
#define ENV_Alert2_ID                 22
#define ENV_Alert3_ID                 23
#define ENV_Alerts4_ID                24
#define ENV_Alerts5_ID                25
#define ENV_Alert6_ID                 26
#define ENV_OTA_XML_URL_ID            27
#define ENV_BSL_OTA_URL_ID            28
#define ENV_BT_LINK_KEY_ID            29
#define ENV_MavidVer_ID               30
#define ENV_AppSecurityKey_ID         31
#define ENV_FriendlyName_ID           32
#define ENV_SAC_SSID_ID               33
#define ENV_ssid_1_ID                 34
#define ENV_passphrase_1_ID           35
#define ENV_BT_REM_DEV_DB_ID          36
#define ENV_ssid_2_ID                 37
#define ENV_passphrase_2_ID           38
#define ENV_ssid_3_ID                 39
#define ENV_passphrase_3_ID           40
#define ENV_ssid_4_ID                 41
#define ENV_passphrase_4_ID           42
#define ENV_wifiprofhist_ID           43
#define ENV_Auto_FW_update_enable_ID  44
#define ENV_fact_test_level_ID        45
#define ENV_Device_Key_ID             46
#define ENV_Device_Cert_ID            47
#define ENV_Root_C_ID                 48
#define ENV_Brand_ID                  49
#define ENV_Model_ID                  50
#define ENV_ProductType_ID            51
#define ENV_IoT_ProductKey_ID         52
#define ENV_IoT_EndpointUrl_ID        53
#define ENV_IoT_CVMUrl_ID             54
#define ENV_AudioQ_ID                 55
