#ifndef _FEATURE_LIST_LED_H_
#define _FEATURE_LIST_LED_H_


/* Important Note : Add New Entry at last
   Do not change order */

#ifdef LED_CONFIG_HDST
typedef enum
{
    DEVICE_STATE_IDLE  = 0,
    DEVICE_STATE_BOOTING,
    AVS_LED_STATE_CONNECTED,
    AVS_LED_STATE_DISCONNECTED,
    AVS_LED_STATE_RECORDING,
    AVS_LED_STATE_RECEIVING,
    AVS_LED_STATE_PLAYING,
    AVS_LED_STATE_WAITING,
    AVS_LED_STATE_NOTIFY,
    DEVICE_STATE_FATAL_ERROR,
    WIFI_STATE_CONNECTED,
    WIFI_STATE_DISCONNECTED,
    WIFI_STATE_SETUP_MODE,
    MIC_MUTE,
    BATTERY_LOW_STATE,
    POWER_ON,
    SLEEP_LOW_POWER_MODE,
    BATTERY_CHARGING,
    BATTERY_CHARGING_FULL,
    DEVICE_STATE_SHUTDOWN,
    WIFI_CONNECTED_MIC_MUTE,
    WIFI_DISCONNECTED_MIC_MUTE,
    WIFI_CONNECTED_MIC_UNMUTE,
    WIFI_DISCONNECTED_MIC_UNMUTE,
    DEVICE_STATE_READY,
    BATTERY_NORMAL_STATE,
    MIC_UNMUTE,
    BT_LED_CONNECTED,
    BT_LED_DISCONNECTED,
    BT_LED_PAIR,
    WIFI_CONNECTING_MIC_MUTE,
    WIFI_CONNECTING_MIC_UNMUTE,
    BT_CONNECTED_WIFI_OFF,
    BT_CONNECTED_WIFI_ON,
    WIFI_OFF_LED,
    WIFI_ON_LED,
    AVS_LED_ALARM_BEGIN,
    AVS_LED_ALARM_END,
    DND_LED_ENABLED,
    DND_LED_DISABLED
} LedFeatureState;
#elif defined ETON_ENABLED
typedef enum
{
    DEVICE_STATE_IDLE  = 0,
    DEVICE_STATE_BOOTING,
    AVS_LED_STATE_CONNECTED,
    AVS_LED_STATE_DISCONNECTED,
    AVS_LED_STATE_RECORDING,
    AVS_LED_STATE_RECEIVING,
    AVS_LED_STATE_PLAYING,
    AVS_LED_STATE_WAITING,
    AVS_LED_STATE_NOTIFY,
    DEVICE_STATE_FATAL_ERROR,
    WIFI_STATE_CONNECTED,
    WIFI_STATE_DISCONNECTED,
    WIFI_STATE_SETUP_MODE,
    MIC_MUTE,
    BATTERY_LOW_STATE,
    POWER_ON,
    SLEEP_LOW_POWER_MODE,
    BATTERY_CHARGING,
    BATTERY_CHARGING_FULL,
    DEVICE_STATE_SHUTDOWN,
    WIFI_CONNECTED_MIC_MUTE,
    WIFI_DISCONNECTED_MIC_MUTE,
    WIFI_CONNECTED_MIC_UNMUTE,
    WIFI_DISCONNECTED_MIC_UNMUTE,
    DEVICE_STATE_READY,
    BATTERY_NORMAL_STATE,
    MIC_UNMUTE,
    BT_LED_CONNECTED,
    BT_LED_DISCONNECTED,
    BT_LED_PAIR,
    WIFI_CONNECTING_MIC_MUTE,
    WIFI_CONNECTING_MIC_UNMUTE,
    BT_CONNECTED_WIFI_OFF,
    BT_CONNECTED_WIFI_ON,
    WIFI_OFF_LED,
    WIFI_ON_LED,
    AVS_LED_ALARM_BEGIN,
    AVS_LED_ALARM_END,
    DND_LED_ENABLED,
    DND_LED_DISABLED,
    BATTERY_CHARGING_REMOVED,
    BT_LED_CONNECTED_AVS_LOGIN,
    BT_LED_CONNECTED_AVS_NOT_LOGIN,
    BT_LED_PAIR_TIMEOUT
} LedFeatureState;
#elif defined(LED_CONFIG_V2)
typedef enum
{
	/* COMMON STATES */
	DEVICE_STATE_IDLE = 0,
	DEVICE_STATE_BOOTING,
	DEVICE_STATE_FATAL_ERROR,

	/* BATTERY GROUP STATES */
	BATTERY_LOW_STATE,
	BATTERY_NORMAL_STATE,
	BATTERY_CHARGING,
	BATTERY_CHARGING_FULL,
	LOW_POWER_ENTRY,
	LOW_POWER_EXIT,
	DEVICE_STATE_SHUTDOWN,

	/* BT GROUP STATES */
	BT_LED_CONNECTING,
	BT_LED_CONNECTED,
	BT_LED_DISCONNECTED,
	BT_LED_PAIR,
	BT_CONNECTED_WIFI_OFF,
	BT_DISCONNECTED_WIFI_OFF,
	BT_LED_ACTION_OFF,
	BT_LED_ACTION_ON,

	/* WIFI GROUP STATES */
	WIFI_STATE_CONNECTING,
	WIFI_STATE_CONNECTED,
	AVS_LED_NOLOGIN,
	AVS_LED_LOGIN,
	DEVICE_LED_STATE_AVS,
	WIFI_STATE_SETUP_MODE,
	WIFI_STATE_DISCONNECTED,
	AVS_LED_STATE_DISCONNECTED,
	WIFI_OFF_LED,
	WIFI_ON_LED,

	/* MIC GROUP STATES */
	MIC_MUTE,
	MIC_UNMUTE,

	/* AVS GROUP STATES */
        AVS_LED_STATE_CONNECTING,
        AVS_LED_STATE_CONNECTED,
        AVS_LED_STATE_RECORDING,
	AVS_LED_STATE_RECEIVING,
	AVS_LED_STATE_PLAYING,
	AVS_LED_STATE_WAITING,
	AVS_LED_STATE_NOTIFY,
	AVS_LED_ALARM_BEGIN,
	AVS_LED_ALARM_END,
	DND_LED_ENABLED,
	DND_LED_DISABLED,
    ALL_LED_OFF_ENTRY,
    ALL_LED_OFF_EXIT,
	DEVICE_STATE_READY,

	/*SOURCE MODE CHANGE STATES*/
	BT_MODE_ENTRY,
	BT_MODE_EXIT,
	ZIGBEE_MODE_ENTRY,
	ZIGBEE_MODE_EXIT,
	WIFI_MODE_ENTRY,
	WIFI_MODE_EXIT,
	ZIGBEE_MODE_CONNECTING,
	ZIGBEE_MODE_CONNECTED,
    BT_PLAY_LED_STATE,
    BT_PAUSED_LED_STATE,
    WIFI_STATE_IDLE

}LedFeatureState;
#else
typedef enum
{
    DEVICE_STATE_IDLE     = 0,
    DEVICE_STATE_BOOTING,
    AVS_LED_STATE_CONNECTED,
    AVS_LED_STATE_DISCONNECTED,
    AVS_LED_STATE_RECORDING,
    AVS_LED_STATE_RECEIVING,
    AVS_LED_STATE_PLAYING,
    AVS_LED_STATE_WAITING,
    AVS_LED_STATE_NOTIFY,
    DEVICE_STATE_FATAL_ERROR,
    WIFI_STATE_CONNECTED,
    WIFI_STATE_DISCONNECTED,
    WIFI_STATE_SETUP_MODE,
    MIC_MUTE,
    BATTERY_LOW_STATE,
    DEVICE_STATE_SHUTDOWN,
    MIC_UNMUTE,
    BATTERY_NORMAL_STATE,
    BT_LED_CONNECTED,
    BT_LED_DISCONNECTED,
    BT_LED_PAIR,
    WIFI_STATE_CONNECTING,
    AVS_LED_ALARM_BEGIN,
    AVS_LED_ALARM_END,
    LOW_POWER_ENTRY,
    LOW_POWER_EXIT,
    ALL_LED_OFF_ENTRY,
    ALL_LED_OFF_EXIT,
    BT_LED_ACTION_ON,
    BT_LED_ACTION_OFF,
    DND_LED_ENABLED,
    DND_LED_DISABLED,
    BT_LED_PAIR_TIMEOUT,
    WIFI_OFF_LED,
    WIFI_ON_LED,
    BT_MODE_ENTRY,
	BT_MODE_EXIT,
	ZIGBEE_MODE_ENTRY,
	ZIGBEE_MODE_EXIT,
	WIFI_MODE_ENTRY,
	WIFI_MODE_EXIT,
	ZIGBEE_MODE_CONNECTING,
	ZIGBEE_MODE_CONNECTED
} LedFeatureState;
#endif


typedef enum
{
  COMBI_000 = 0,
  COMBI_00B,
  COMBI_0G0,
  COMBI_0GB,
  COMBI_R00,
  COMBI_R0B,
  COMBI_RG0,
  COMBI_RGB,
  COMBI_YG0,
  COMBI_RY0,
  COMBI_0YB,
  COMBI_0GY,
  COMBI_Y0B,
  COMBI_R0Y,
  COMBI_YYY,
  COMBI_PURPLE,
  COMBI_ORANGE,
  COMBI_PURPLE_OFF,
  COMBI_ORANGE_OFF,
  COMBI_R00_BREATH,
  COMBI_00B_BREATH,
  COMBI_RGB_BREATH,
  COMBI_PWM000
}Combi_TypeDef;

int SetLedFeature(LedFeatureState StateID);

#endif /* _FEATURE_LIST_LED_H_ */

